[functions]
included_files = ["./netlify/functions/templates/**"]
node_bundler = "esbuild"
external_node_modules = ["@sparticuz/chromium"]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/download/app/*"
to = "https://github.com/hoppscotch/releases/releases/latest/download/:splat"
status = 301
force = true

[[redirects]]
from = "/download/desktop/*"
to = "https://github.com/hoppscotch/releases/releases/latest/download/:splat"
status = 301
force = true

[[redirects]]
from = "/download/agent/*"
to = "https://github.com/hoppscotch/agent-releases/releases/latest/download/:splat"
status = 301
force = true
